### ISSUE TITLE
Replace old banners with Resources in content/post

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/GDquest-website#57]
Djrm added support for hugo's new Resources feature for article and page banners - at build time, if the page has a defined resource, hugo will generate a low resolution copy of the banner image to blur and scale in the page's background - important for performance reasons.

![image](https://user-images.githubusercontent.com/12694995/45025868-a9baf980-b077-11e8-94e1-94c5e8157494.png)

![image](https://user-images.githubusercontent.com/12694995/45025901-c22b1400-b077-11e8-907a-4f82c29a4c02.png)

Everything in content/post uses the old system, a custom banner variable:

![image](https://user-images.githubusercontent.com/12694995/45025843-94de6600-b077-11e8-90b7-2939bf23d6fb.png)

This task is to:

1. [ ] Replace all instances of the `banner:` variable with the new `resources:` system
2. [ ] Make the post/single template use the "modules/banner" instead

**Comment by guilhermehto** [comment]
By removing `banner: ` the listing does not work correctly: 
![image](https://user-images.githubusercontent.com/20494771/45380587-70cfd700-b5d9-11e8-9957-8b858f009c6e.png)

Should I modify the list or keep `banner:`?

**Comment by guilhermehto** [comment]
> just gotta figure out which template to update

Alright, will do.

The posts are updated. In some of the older ones, the alt tag was different than the name (which has to be equal to banner as that's what we look for in the templates), to work around it I took this approach:

posts:

```yaml
# with alt defined 
resources:
  - src: banner.jpg
    name: banner
    params:
        alt: "A diagram showing the condition "hit", linked to the word "damage", next to the Godot engine 
and Kickstarter logos"

#without alt:
resources:
  - src: banner.jpg
    name: banner
```


single.html:
```html
{{ with (.Resources.GetMatch "banner") }}
            {{ if .Params.Alt }}
                <img src="{{ .Permalink }}" alt="{{ .Params.Alt }}">
            {{ else }}
                <img src="{{ .Permalink }}" alt="{{ .Name }}">
            {{ end }}
        {{ end }}
```
